language: java
sudo: required
dist: trusty
install: true

services:
- postgresql
- mysql

addons:
  apt:
    packages:
      - dpkg
  postgresql: "9.4"
  sonarcloud:
    organization: "noraui"
  firefox: latest
  chrome: stable
  
jdk:
- oraclejdk8
- openjdk8
- oraclejdk11
- openjdk11

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- chmod +x test/run.sh
- chmod +x test/after_success.sh
- psql -c 'create database noraui owner travis;' -U postgres
- psql -U travis -d noraui -a -f config/noraui-db.sql
- mysql -e 'CREATE DATABASE noraui;'
- mysql --user=travis noraui < config/noraui-db.sql > output.tab
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%cN")"
- curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py

script:
- test/run.sh

after_success:
- python travis_after_all.py https://api.travis-ci.com
- export $(cat .to_export_back)
- |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All jobs succeeded! PUBLISHING..."
        else
          echo "Some jobs failed"
        fi
      fi
- test/after_success.sh

after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS

cache:
  directories:
    - $HOME/.m2/repository

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8f036338cae1f916682
    on_failure: always  # options: [always|never|change] default: always
