language: java
sudo: false
install: true

services:
- mysql
- postgresql

addons:
  sonarqube:
    organization: "noraui"

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh
- chmod +x test/after_success.sh
- mysql -e 'CREATE DATABASE noraui;'
- psql -c 'create database noraui;' -U postgres
 
script:
- test/run.sh

after_success: test/after_success.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8f036338cae1f916682
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
