sudo: false

language: java

jdk:
- oraclejdk8

before_install:
 - chmod +x test/run.sh
 
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
 
script:
- test/run.sh

after_script:
- travis version
