sudo: false

language: java

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- echo "y" | travis login --github-token $GH_TOKEN
 
script:
- test/run.sh

after_script:
- travis version
