sudo: false

language: java

env:
  global:
    secure: "62777a7617b560275d2057a6ce1ab95822cd8b8a"

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- echo "y" | travis login --github-token "62777a7617b560275d2057a6ce1ab95822cd8b8a"
 
script:
- test/run.sh

after_script:
- travis version
- travis logs
