language: java
sudo: false
install: true

services:
- postgresql
- mysql

addons:
  postgresql: "9.4"
  sonarqube:
    organization: "noraui"

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh
- chmod +x test/after_success.sh
- psql -c 'create database noraui owner travis;' -U postgres
- psql -U travis -d noraui -a -f config/noraui-db.sql
- mysql -e 'CREATE DATABASE noraui;'
- mysql --user=travis noraui < config/noraui-db.sql > output.tab

script:
- test/run.sh

after_success: 
- test/after_success.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8f036338cae1f916682
    on_failure: always  # options: [always|never|change] default: always
