sudo: false

language: java

jdk:
- oraclejdk8

before_install:
- chmod +x test/run.sh
- chmod +x test/after_success.sh
 
script:
- test/run.sh

after_success: test/after_success.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8f036338cae1f916682
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
